version: '3.5'
services:
  imgpush:
    ports:
        - "5000:5000"
    build: .
    volumes:
      - ./app:/app
      - ./images:/images
      - ./cache:/cache
    environment:
      - SERVICE_FQDN_IMGPUSH_5000
