version: '3.5'
services:
  imgpush:
    build: .
    volumes:
      - imgpush-app:/app
      - imgpush-images:/app/images
      - imgpush-cache:/app/cache
    environment:
      - SERVICE_FQDN_IMGPUSH_5000
