version: '3.5'
services:
  imgpush:
    image: unsend/unsend:latest
    expose:
      - 5000
    volumes:
      - imgpush-app:/app
      - imgpush-images:/images
      - imgpush-cache:/cache
    environment:
      - SERVICE_FQDN_UNSEND_3000
